# Generated by Django 5.0.10 on 2024-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('index_no', models.CharField(blank=True, db_column='Index_No', max_length=45, null=True)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
